### ISSUE TITLE
Failed to source `luasnip.lua`

### ISSUE THREAD

**Issue by jwangtobeno1** [ayamir/nvimdots#1131]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

0.9.5

### Branch info

main (Default/Latest)

### Minimal (user) folder structure required to reproduce the issue

```console
no modify
```

### Minimal config with steps on how to reproduce the issue

The following warning will be displayed every time I start nvim

![image](https://github.com/ayamir/nvimdots/assets/69038155/7d6c2c28-9abf-433f-9537-97f0fad0dfdc)

### Expected behavior

turn off waring

**Comment by ayamir** [comment]
A related issue is fixed: https://github.com/ayamir/nvimdots/issues/1030

**Comment by jwangtobeno1** [comment]
The problem remains. Whenever I open a file with nvim and press `i` or `a` or `o`  to enter edit mode, this warning will appear.

![Snipaste_2024-01-06_21-45-49](https://github.com/ayamir/nvimdots/assets/69038155/ade1fe0a-8989-4337-8bd6-a2e62e75dae2)

![image](https://github.com/ayamir/nvimdots/assets/69038155/23fc22dc-671d-4546-bdc5-46e9473c9f7a)

**Comment by ayamir** [comment]
Can't repro indeed. Try removing the dir of `LuaSnip` and reinstall it?

**Comment by jwangtobeno1** [comment]
> Can't repro indeed. Try removing the dir of `LuaSnip` and reinstall it?

do the following?

1. `rm -rf  .../.config/.../luasnip.lua`
2. sudo pacman -S luasnip

**Comment by Jint-lzxy** [comment]
> do the following?

u shouldn't use ur package mgr to install `LuaSnip`. Just fire up `neovim` and let `lazy` do the work for u.

**Comment by jwangtobeno1** [comment]
> Can't repro indeed. Try removing the dir of `LuaSnip` and reinstall it?

it's ok

**Comment by toyuanx** [comment]
> > Can't repro indeed. Try removing the dir of `LuaSnip` and reinstall it?
> 
> it's ok

how do you uninstall and reinstall luasnip?
